global:
  scrape_interval: 15s # Imposta l'intervallo di scraping a 15 secondi

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['ml-exporter:8000']  # Indirizzo dell'exporter del modello ML