name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_train:
    runs-on: ubuntu-latest

    permissions:
      contents: write # permette al workflow di accedere al contenuto del repository
      id-token: write # Permette al workflow di generare un ID token per l'autenticazione con servizi esterni

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu #Installo PyTorch nella versione CPU
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Run training
      run: |
        python src/train.py --num_train_epochs 1 --max_samples 1000
    
    - name: Installazione libreria per CD
      run: |
        # Necessario per interagire con l'Hub di Hugging Face
        pip install huggingface_hub

    - name: Carico il Modello su Hugging Face Hub
      # Imposto una condizione per cui eseguo il deploy solo se il commit Ã¨ sul branch 'main' e se i test precedenti hanno avuto successo
      if: success() && github.ref == 'refs/heads/main'
      env:
        # Usao il Secret che ho creato per questo scopo
        HF_ACCESS_TOKEN: ${{ secrets.HF_TOKEN }} 
      run: |
        pip install huggingface_hub
        python -c "from huggingface_hub import login; login('${{ secrets.HF_TOKEN }}')"
        python -c "from huggingface_hub import HfApi; api = HfApi(); api.upload_folder(folder_path='./trained_model', repo_id='HRick17/machine-innovators', repo_type='model', commit_message='Deploy CI/CD automatico')"